"""Original bounded coupled-absolute grid; maxima never change the primary model."""
from __future__ import annotations

import argparse
from datetime import datetime,timezone
import hashlib
import io
import json
import math
from pathlib import Path
import uuid

import numpy as np
import pandas as pd

from .backtest_workflow import admit_sources,prepare_inputs,run_backtest_study,validate_config
from .config import SwissquoteStandardFeeSchedule
from .historical import simulate,metrics
from .inflow_workflow import sha256,source_hashes,verify_run,write_json


def scenario_definitions(settings,baseline):
    if (settings['schema_version']!=1 or settings['policy']!='legacy_absolute' or settings['period']!='full'
        or settings['leverage_levels']!=[1.,1.25] or any(x not in baseline['leverage_levels'] for x in settings['leverage_levels'])
        or settings['sleeve_bands']!=[.03,.05] or settings['leverage_bands']!=[.05,.1,.15]
        or settings['definition_target_leverage']!=1.25):
        raise ValueError('preserved bounded grid and coupled absolute policy required')
    sleeves=list(baseline['target_weights']);vectors=settings['weight_vectors'];seen=set();rows=[]
    if len(vectors)!=25:raise ValueError('original twenty-five weight definitions required')
    for i,weights in enumerate(vectors,start=1):
        if (set(weights)!=set(sleeves) or any(not math.isfinite(x) or x<=0 for x in weights.values())
            or abs(math.fsum(weights.values())-1)>1e-10):raise ValueError('positive complete grid weights must sum to one')
        values=tuple(weights[s] for s in sleeves)
        if values in seen:raise ValueError('distinct grid weight vectors required')
        seen.add(values)
        for sb in settings['sleeve_bands']:
            for lb in settings['leverage_bands']:
                label=f'W{i:02d}-SB{int(sb*100):02d}-LB{int(lb*100):02d}'
                rows.append(dict(scenario_id=label,**{f'{s}_weight':v for s,v in zip(sleeves,values)},
                    sleeve_band=sb,target_leverage=settings['definition_target_leverage'],leverage_band=lb,is_baseline=label==settings['definition_baseline_scenario_id']))
    frame=pd.DataFrame(rows)
    if int(frame.is_baseline.sum())!=1:raise ValueError('unique original definition-baseline label required')
    data=frame.to_csv(index=False,float_format='%.12f',lineterminator='\n').encode()
    if hashlib.sha256(data).hexdigest()!=settings['definition_source_sha256']:
        raise ValueError('generated grid differs from captured original definition hash')
    # The frozen producer read the twelve-decimal CSV before simulation. Reload
    # generated bytes at that same boundary rather than admitting hidden digits.
    return pd.read_csv(io.BytesIO(data))


def account_check(run):
    h=run.history;e=run.events
    position_error=float((h.filter(regex='^position_').sum(axis=1)-h.gross_assets_usd).abs().max())
    equity_error=float((h.gross_assets_usd-h.debt_usd-h.equity_usd).abs().max())
    charge_error=abs(float(e.fees_usd.sum())-float(h.cumulative_transaction_cost_usd.iloc[-1]))
    funding_error=abs(float(h.financing_cost_usd.sum())-float(h.cumulative_financing_cost_usd.iloc[-1]))
    if run.status!='complete' or min(h.equity_usd)<=0 or max(position_error,equity_error,charge_error,funding_error)>1e-6:
        raise ValueError('incomplete or unreconciled hindsight account')
    return dict(observations=len(h),minimum_equity_usd=float(h.equity_usd.min()),
        maximum_position_identity_error_usd=position_error,maximum_equity_identity_error_usd=equity_error,
        event_fee_reconciliation_error_usd=charge_error,funding_reconciliation_error_usd=funding_error)


def summarize_maxima(table):
    rows=[];selection=[]
    for lev,g in table.groupby('leverage',sort=False):
        value=float(g.cagr.max());tied=g[g.cagr==value]
        for position,(_,r) in enumerate(tied.iterrows(),start=1):
            rows.append(dict(leverage=lev,scenario_id=r.scenario_id,cagr=float(r.cagr),
                core_weight=r.core_weight,momentum_weight=r.momentum_weight,quality_weight=r.quality_weight,value_weight=r.value_weight,
                sleeve_band=r.sleeve_band,leverage_band=r.leverage_band,exact_tie_count=len(tied),display_representative=position==1))
        selection.append(dict(leverage=float(lev),maximum_cagr=value,exact_tie_scenarios=tied.scenario_id.tolist(),
            display_scenario_id=str(tied.scenario_id.iloc[0]),tie_rule='First original grid row is the display representative; all exact computed ties retained.'))
    return pd.DataFrame(rows),selection


def hindsight_comparison(returns,reference,baseline,settings):
    definitions=scenario_definitions(settings,baseline);boundaries=baseline['periods']['full'];ret=returns.loc[boundaries['start']:boundaries['end']].copy()
    if len(ret)<4 or str(ret.index[0].date())!=boundaries['start'] or str(ret.index[-1].date())!=boundaries['end']:
        raise ValueError('complete declared full-period grid calendar required')
    ret.iloc[0]=0.;sleeves=list(baseline['target_weights']);fee=SwissquoteStandardFeeSchedule(**baseline['fee_schedule'])

    def account(cols,weights,lev,policy,sb,lb):
        run=simulate(ret[cols],reference,weights,lev,policy,margin=baseline['borrowing_margin_annual'],sleeve_band=sb,leverage_band=lb,
            initial_equity_usd=baseline['initial_equity_usd'],fee_schedule=fee)
        if len(run.history)!=len(ret):raise ValueError('incomplete hindsight path')
        return run

    market=account(['core'],[1.],1.,'no_sleeve',baseline['sleeve_band'],baseline['leverage_band'])
    rows=[];events=[];checks=[]
    for lev in settings['leverage_levels']:
        for g in definitions.to_dict('records'):
            weights=[g[f'{s}_weight'] for s in sleeves];run=account(sleeves,weights,lev,settings['policy'],g['sleeve_band'],g['leverage_band'])
            check=account_check(run);label=f'{lev:.2f}__{g["scenario_id"]}'
            rows.append(dict(scenario_id=g['scenario_id'],leverage=lev,**{f'{s}_weight':v for s,v in zip(sleeves,weights)},
                sleeve_band=g['sleeve_band'],leverage_band=g['leverage_band'],**metrics(run,reference,market,weights)))
            checks.append(dict(run_id=label,leverage=lev,scenario_id=g['scenario_id'],**check));events.append(run.events.assign(run_id=label))
    table=pd.DataFrame(rows);maximum,selection=summarize_maxima(table);histories=[]
    # Replay one display representative per exposure for readable account evidence.
    # This selects evidence only, never changes a baseline weight/band configuration.
    for selected in selection:
        g=definitions[definitions.scenario_id==selected['display_scenario_id']].iloc[0];weights=[g[f'{s}_weight'] for s in sleeves]
        run=account(sleeves,weights,selected['leverage'],settings['policy'],g.sleeve_band,g.leverage_band);account_check(run)
        if metrics(run,reference,market,weights)['cagr']!=selected['maximum_cagr']:raise ValueError('display replay differs from grid result')
        histories.append(run.history.reset_index().assign(run_id=f'{selected["leverage"]:.2f}__{selected["display_scenario_id"]}'))
    return dict(metrics=table,definitions=definitions,events=pd.concat(events,ignore_index=True),checks=pd.DataFrame(checks),
        maxima=maximum,selected_histories=pd.concat(histories,ignore_index=True),selection=selection,
        scope=dict(policy=settings['policy'],definition_target_leverage='Preserved definition metadata; actual exposure is each result row leverage.',
            coupled_reset='Legacy leverage-only events also reset target sleeve weights, unlike the current decoupled primary.',
            wealth_base='Original committed capital, net investor returns/entry costs, full common period and baseline funding/trading assumptions.',
            unchanged_primary_weights=baseline['target_weights'],unchanged_primary_policy=baseline['primary_policy'],no_automatic_primary_selection=True,
            limitations=['300 parameter labels include unlevered leverage-band duplicates; not 300 independent economic observations.',
                'Full-sample CAGR maxima only within this bounded family, not global or future optima.',
                'No new absolute-decoupled search, statistical multiple-testing correction or final report.']))


def run_hindsight(raw_root,baseline_path,sources_path,settings_path,output):
    output=Path(output)
    if output.exists():raise FileExistsError('choose a new hindsight output directory')
    paths=[baseline_path,sources_path,settings_path];captured={Path(p).name:Path(p).read_bytes() for p in paths}
    if len(captured)!=3:raise ValueError('distinct configuration filenames required')
    baseline,spec,settings=[json.loads(captured[Path(p).name]) for p in paths]
    validate_config(baseline);scenario_definitions(settings,baseline)
    output.mkdir(parents=True);(output/'config').mkdir()
    for name,data in captured.items():(output/'config'/name).write_bytes(data)
    code=source_hashes();manifest=dict(schema_version=1,run_id=str(uuid.uuid4()),status='running',figures_included=False,
        started_at_utc=datetime.now(timezone.utc).isoformat(),code=code,
        scope='Original bounded 300-label coupled-absolute hindsight grid regenerated from original inputs; no primary selection or final reports.',
        configuration_snapshots={f'config/{name}':sha256(output/'config'/name) for name in captured},artifacts={})
    write_json(output/'run_manifest.json',manifest)
    try:
        core=run_backtest_study(raw_root,output/'config'/Path(baseline_path).name,output/'config'/Path(sources_path).name,output/'core')
        inputs=output/'grid_inputs';inputs.mkdir();returns,reference=prepare_inputs(raw_root,admit_sources(raw_root,spec),spec,baseline,inputs)
        result=hindsight_comparison(returns,reference,baseline,settings)
        for key,name in [('metrics','hindsight_grid.csv'),('definitions','scenario_definitions.csv')]:result[key].to_csv(output/name,index=False,float_format='%.12f',lineterminator='\n')
        for key,name in [('events','grid_events.csv'),('checks','grid_account_checks.csv'),('maxima','bounded_maxima.csv'),('selected_histories','display_account_histories.csv')]:result[key].to_csv(output/name,index=False,lineterminator='\n')
        write_json(output/'grid_definitions.json',dict(settings=settings,selection=result['selection'],scope=result['scope']))
        (output/'README.md').write_text('# Bounded Historical Grid\n\nOriginal 25-weight/two-sleeve-band/three-leverage-band definitions at 1x and 1.25x, using coupled legacy absolute resets. '
            'All computed maximum ties remain visible; display account selection does not change the main strategy. No future optimality claim.\n\n'
            '[300 metrics](hindsight_grid.csv) · [150 definitions](scenario_definitions.csv) · [Maxima and ties](bounded_maxima.csv) · [Account checks](grid_account_checks.csv) · '
            '[All events](grid_events.csv) · [Two display accounts](display_account_histories.csv) · [Scope](grid_definitions.json) · [Fresh core](core/README.md) · [Manifest](run_manifest.json)\n')
        admit_sources(raw_root,spec)
        if source_hashes()!=code:raise RuntimeError('source changed during hindsight reconstruction')
        manifest['artifacts']={str(p.relative_to(output)):sha256(p) for p in sorted(output.rglob('*')) if p.is_file() and p!=output/'run_manifest.json' and p.relative_to(output).parts[0]!='config'}
        manifest.update(status='complete',finished_at_utc=datetime.now(timezone.utc).isoformat(),raw_sources=core['raw_sources'],
            counts=dict(grid_cases=len(result['metrics']),scenario_definitions=len(result['definitions']),account_checks=len(result['checks']),trade_events=len(result['events']),
                exact_maximum_rows=len(result['maxima']),display_history_rows=len(result['selected_histories']),core_cases=core['counts']['policy_cases']))
        write_json(output/'run_manifest.json',manifest);verify_run(output)
    except Exception as error:
        manifest.update(status='failed',failure=dict(type=type(error).__name__,message=str(error)));write_json(output/'run_manifest.json',manifest);raise
    return manifest


def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--raw-root',type=Path,required=True);p.add_argument('--output',type=Path,required=True)
    for key,name in [('baseline','backtest_absolute_decoupled_2026-10-05.json'),('sources','backtest_sources.json'),('settings','backtest_legacy_hindsight_2026-10-05.json')]:p.add_argument('--'+key,type=Path,default=Path('config')/name)
    a=p.parse_args();m=run_hindsight(a.raw_root,a.baseline,a.sources,a.settings,a.output);print(json.dumps(dict(run_id=m['run_id'],status=m['status'],counts=m['counts']),indent=2))


if __name__=='__main__':main()
